# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [4]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [ ]:
np.version.version

#### Q3 : Créer un vecteur nul de taille 10

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [4]:
L2 = np.zeros(10)
L2[3] = 1

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [8]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [9]:
np.arange(10, 51)[::1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [6]:
np.matrix('1 2 3; 3 4 5; 6 7 8')

matrix([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [9]:
np.identity(3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [12]:
np.array([x for x in range(27)]).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [17]:
array = np.array(np.random.randint(0, 100, 100)).reshape(10, 10)
print(np.max(array))
print(np.min(array))

99
0


#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [59]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [35]:
Z = np.random.randint(0, 50, 5)
np.sum(Z)

159

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [36]:
Z = np.random.randint(0, 50, 5)
np.mean(Z)

25.8

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [41]:
l = [x for x in range(11)]
len(l)

11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [63]:
np.random.rand(10)

array([0.29519629, 0.75296669, 0.07555606, 0.91676553, 0.86559729,
       0.00273821, 0.73010608, 0.43392898, 0.90258541, 0.31068118])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [50]:
a = np.random.randint(2, 10, 5)
b = np.random.randint(2, 10, 5)
np.array_equal(a, b)

False

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [57]:
array = np.array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2,], dtype=np.float32)
np.array(array, dtype=np.int32)

array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2])

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [64]:
b = np.array([x for x in range(25)]).reshape(5, 5)
A = (A - mean(A)) / std(A)

NameError: name 'A' is not defined

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)